In [9]:
import numpy as np
from IPython.display import display

a1 = np.array([1,2,3])
print(a1)
type(a1)

[1 2 3]


numpy.ndarray

In [5]:
a2 = np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a3 = np.zeros((2,3))
a4 = np.ones((2,3))
display(a3)
display(a4)

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
a5 = np.linspace(0,1,10)
display(a5)
a5.dtype

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

dtype('float64')

In [16]:
a3.shape

(2, 3)

In [18]:
a1D = np.array([1,2,3])
a2D = np.array([[1,2,3]])
display(a1D.shape)
display(a2D.shape)

(3,)

(1, 3)

In [21]:
#Son los dos arrays iguales?
np.array_equal(a1D,a2D)

False

In [23]:
#Reshaping
new_dims = (1,a1D.shape[0])
a = a1D.reshape(new_dims)
np.array_equal(a,a2D)

True

In [24]:
a = np.array([[1,0,3],[4,3,5],[6,10,-1]])
a

array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

In [25]:
a[2,1]

10

In [26]:
a = np.arange(10)
b = np.eye(3)
display(a);display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
a[:5]

array([0, 1, 2, 3, 4])

In [29]:
b[0:2,1]

array([0., 1.])